In [1]:
import torch
import numpy as np

In [7]:
np_data = np.arange(6).reshape((2, 3))
# numpy -> torch
torch_data = torch.from_numpy(np_data)
# torch -> numpy
tensor2array = torch_data.numpy()

print('\n numpy array : \n', np_data, 
      '\n torch tensor :\n', torch_data,
      '\n tensor to array : \n', tensor2array, 
      )


 numpy array : 
 [[0 1 2]
 [3 4 5]] 
 torch tensor :
 tensor([[0, 1, 2],
        [3, 4, 5]]) 
 tensor to array : 
 [[0 1 2]
 [3 4 5]]


In [13]:
# abs
data = [-1, -2, 1, 2]
tensor = torch.FloatTensor(data)
print("## abs ##")
print(f"numpy abs :\n{np.abs(data)} ")
print(f"torch abs :\n{torch.abs(tensor)} ")
# not working.. torch abs input must be Tensor
print(f"torch abs to another type : \n{torch.abs(data)}") 

## abs ##
numpy abs :
[1 2 1 2] 
torch abs :
tensor([1., 2., 1., 2.]) 


TypeError: abs(): argument 'input' (position 1) must be Tensor, not list

In [20]:
# tensor object have methods for transform itself
print(tensor.abs())
print(tensor.sin())
print(tensor.acos())
print(tensor.sigmoid())
print(tensor.mean())
print(tensor.var())
print(tensor.tanh())
print(tensor.relu())

tensor([1., 2., 1., 2.])
tensor([-0.8415, -0.9093,  0.8415,  0.9093])
tensor([3.1416,    nan, 0.0000,    nan])
tensor([0.2689, 0.1192, 0.7311, 0.8808])
tensor(0.)
tensor(3.3333)
tensor([-0.7616, -0.9640,  0.7616,  0.9640])
tensor([0., 0., 1., 2.])


In [23]:
# matrix multiblication
data = [[1, 2], [3, 4]]
tensor = torch.FloatTensor(data)

print(f"np.matmul : \n{np.matmul(data, data)}")
print(f"numpy : \n{torch.mm(tensor, tensor)}")

np.matmul : 
[[ 7 10]
 [15 22]]
numpy : 
tensor([[ 7., 10.],
        [15., 22.]])


torch.dot(tensor1, tensor2) -> float  

두 tensor의 inner product를 계산. 이때 두 tensor는 반드시 1-D vector 이어야 함.

In [29]:
# tensor matrix multiplication
tensor.mm(tensor)

tensor([[ 7., 10.],
        [15., 22.]])

In [39]:
# tensor elementwise multiplication
tensor*tensor

tensor([[ 1.,  4.],
        [ 9., 16.]])

In [40]:
# tensor dot product
torch.dot(torch.Tensor([2, 3]), torch.Tensor([2, 1]))

tensor(7.)

In [28]:
# torch dot : can't broad casting
data = np.array(data)
tensor = torch.Tensor(data)
print("dot")
print(f"numpy.dot : \n{data.dot(data)}")
# torch dot : only works for 1-dimentional tensor. 
print(f"torch.dot : {torch.dot(tensor.dot(tensor))}")


dot
numpy.dot : 
[[ 7 10]
 [15 22]]


RuntimeError: 1D tensors expected, but got 2D and 2D tensors