torch에서 variable은 computational graph를 구성하기위해 존재합니다. 이때 graph는 tensorflow나 theano의 static graph가 아닌 dynamic graph이기 때문에 torch는 placeholder를 가지고 있지 않습니다.  
torch는 단지 variable을 computational graph에 통과시키기만 할 뿐입니다. 


In [1]:
import torch
from torch.autograd import Variable

In [2]:
# build a tensor
tensor = torch.FloatTensor(([1, 2], [3, 4]))
# build a variable, usually for compute gradients 
variable = Variable(tensor, requires_grad = True)

print(tensor)
print(variable)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


아직까직은 tensor와 variable이 서로 같아 보입니다. 
하지만, variable은 graph의 일부분이고, auto-gradient의 일부분 입니다

In [3]:
t_out = torch.mean(tensor*tensor) # mean of elementwise product
v_out = torch.mean(variable*variable)
print(t_out)
print(v_out)

tensor(7.5000)
tensor(7.5000, grad_fn=<MeanBackward0>)


In [5]:
v_out.backward()

$$ v_{out} = {{1} \over {4}} sum(variable^2) $$


variable에 대한 gradient :  
$$ {d(v_{out}) \over d(variable)} = {{1} \over {4}} 2 variable = {variable \over 2}$$

`v_out.backward()`를 통해서 구한 radient값은 아래처럼 `variable.grad`를 통해서 볼 수 있습니다

In [8]:
variable.grad

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

variable은 필요에 따라 `variable`, `tensor`, `numpy`로 변환한 값을 볼 수 있습니다

In [13]:
print(f"##variable format## \n{variable}")
print(f"##tenwor format## \n{variable.data}")
print(f"##numpy format## \n{variable.data.numpy()}")

##variable format## 
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
##tenwor format## 
tensor([[1., 2.],
        [3., 4.]])
##numpy format## 
[[1. 2.]
 [3. 4.]]


v_out.backward()를 수행했지만, variable이 새로운 grad값을 받은 것을 주목하세요.

즉,  
`v_out = torch.mean(variable*variable)`
와 같은 코드는  

새로운 변수 `v_out`을 만들어내고, 이를 `variable`과 computational graph로 연결 해 줍니다
